In [173]:
# Carga del dataset
import pandas as pd
df = pd.read_csv("meteo.csv")
print(len(df))
df

142193

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,1.0,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0.2,No
5,2008-12-06,Albury,14.6,29.7,0.2,NaN,NaN,WNW,56.0,W,...,23.0,1009.2,1005.4,NaN,NaN,20.6,28.9,No,0.0,No
6,2008-12-07,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,SW,...,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,No,0.0,No
7,2008-12-08,Albury,7.7,26.7,0.0,NaN,NaN,W,35.0,SSE,...,19.0,1013.4,1010.1,NaN,NaN,16.3,25.5,No,0.0,No
8,2008-12-09,Albury,9.7,31.9,0.0,NaN,NaN,NNW,80.0,SE,...,9.0,1008.9,1003.6,NaN,NaN,18.3,30.2,No,1.4,Yes
9,2008-12-10,Albury,13.1,30.1,1.4,NaN,NaN,W,28.0,S,...,27.0,1007.0,1005.7,NaN,NaN,20.1,28.2,Yes,0.0,No
10,2008-12-11,Albury,13.4,30.4,0.0,NaN,NaN,N,30.0,SSE,...,22.0,1011.8,1008.7,NaN,NaN,20.4,28.8,No,2.2,Yes
11,2008-12-12,Albury,15.9,21.7,2.2,NaN,NaN,NNE,31.0,NE,...,91.0,1010.5,1004.2,8.0,8.0,15.9,17.0,Yes,15.6,Yes
12,2008-12-13,Albury,15.9,18.6,15.6,NaN,NaN,W,61.0,NNW,...,93.0,994.3,993.0,8.0,8.0,17.4,15.8,Yes,3.6,Yes
13,2008-12-14,Albury,12.6,21.0,3.6,NaN,NaN,SW,44.0,W,...,43.0,1001.2,1001.8,NaN,7.0,15.8,19.8,Yes,0.0,No
14,2008-12-16,Albury,9.8,27.7,NaN,NaN,NaN,WNW,50.0,NaN,...,28.0,1013.4,1010.3,0.0,NaN,17.3,26.2,NaN,0.0,No
15,2008-12-17,Albury,14.1,20.9,0.0,NaN,NaN,ENE,22.0,SSW,...,82.0,1012.2,1010.4,8.0,1.0,17.2,18.1,No,16.8,Yes
16,2008-12-18,Albury,13.5,22.9,16.8,NaN,NaN,W,63.0,N,...,65.0,1005.8,1002.2,8.0,1.0,18.0,21.5,Yes,10.6,Yes
17,2008-12-19,Albury,11.2,22.5,10.6,NaN,NaN,SSE,43.0,WSW,...,32.0,1009.4,1009.7,NaN,2.0,15.5,21.0,Yes,0.0,No
18,2008-12-20,Albury,9.8,25.6,0.0,NaN,NaN,SSE,26.0,SE,...,26.0,1019.2,1017.1,NaN,NaN,15.8,23.2,No,0.0,No
19,2008-12-21,Albury,11.5,29.3,0.0,NaN,NaN,S,24.0,SE,...,28.0,1019.3,1014.8,NaN,NaN,19.1,27.3,No,0.0,No
20,2008-12-22,Albury,17.1,33.0,0.0,NaN,NaN,NE,43.0,NE,...,28.0,1013.6,1008.1,NaN,1.0,24.5,31.6,No,0.0,No
21,2008-12-23,Albury,20.5,31.8,0.0,NaN,NaN,WNW,41.0,W,...,24.0,1007.8,1005.7,NaN,NaN,23.8,30.8,No,0.0,No
22,2008-12-24,Albury,15.3,30.9,0.0,NaN,NaN,N,33.0,ESE,...,23.0,1011.0,1008.2,5.0,NaN,20.9,29.0,No,0.0,No
23,2008-12-25,Albury,12.6,32.4,0.0,NaN,NaN,W,43.0,E,...,17.0,1012.9,1010.1,NaN,NaN,21.5,31.2,No,0.0,No
24,2008-12-26,Albury,16.2,33.9,0.0,NaN,NaN,WSW,35.0,SE,...,19.0,1010.9,1007.6,NaN,1.0,23.2,33.0,No,0.0,No
25,2008-12-27,Albury,16.9,33.0,0.0,NaN,NaN,WSW,57.0,NaN,...,28.0,1006.8,1003.6,NaN,1.0,26.6,31.2,No,0.0,No
26,2008-12-28,Albury,20.1,32.7,0.0,NaN,NaN,WNW,48.0,N,...,15.0,1005.2,1001.7,NaN,NaN,24.6,32.1,No,0.0,No
27,2008-12-29,Albury,19.7,27.2,0.0,NaN,NaN,WNW,46.0,NW,...,22.0,1004.8,1004.2,NaN,NaN,21.6,26.1,No,1.2,Yes
28,2008-12-30,Albury,12.5,24.2,1.2,NaN,NaN,WNW,50.0,WSW,...,70.0,1005.6,1003.4,8.0,8.0,12.5,18.2,Yes,0.8,No
29,2008-12-31,Albury,12.0,24.4,0.8,NaN,NaN,W,39.0,WNW,...,28.0,1006.1,1005.1,1.0,NaN,16.9,22.7,No,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142163,2017-05-26,Uluru,14.3,27.6,0.4,NaN,NaN,WNW,39.0,NaN,...,27.0,1020.5,1016.1,4.0,7.0,16.1,27.2,No,0.0,No
142164,2017-05-27,Uluru,9.3,28.0,0.0,NaN,NaN,W,28.0,SSW,...,16.0,1019.9,1016.9,NaN,NaN,16.6,27.3,No,0.0,No
142165,2017-05-28,Uluru,8.0,24.6,0.0,NaN,NaN,E,33.0,SE,...,25.0,1021.7,1018.8,4.0,NaN,13.8,23.5,No,0.0,No
142166,2017-05-29,Uluru,12.7,22.2,0.0,NaN,NaN,E,37.0,E,...,34.0,1024.3,1021.7,8.0,8.0,13.9,21.0,No,0.0,No
142167,2017-05-30,Uluru,9.4,22.7,0.0,NaN,NaN,E,35.0,SE,...,32.0,1026.6,1023.6,8.0,4.0,11.8,22.3,No,0.0,No
142168,2017-05-31,Uluru,5.4,20.5,0.0,NaN,NaN,E,46.0,E,...,32.0,1029.2,1025.3,NaN,NaN,11.1,20.2,No,0.0,No
142169,2017-06-01,Uluru,5.6,19.4,0.0,NaN,NaN,E,43.0,E,...,22.0,1029.6,1027.1,NaN,NaN,9.7,18.3,No,0.0,No
142170,2017-06-02,Uluru,1.5,19.2,0.0,NaN,NaN,E,37.0,ESE,...,18.0,1030.7,1026.7,NaN,NaN,6.8,17.6,No,0.0,No
142171,2017-06-03,Uluru,3.8,19.8,0.0,NaN,NaN,ENE,39.0,ESE,...,22.0,1028.7,1024.1,NaN,NaN,8.6,18.9,No,0.0,No
142172,2017-06-04,Uluru,4.5,18.8,0.0,NaN,NaN,E,31.0,ESE,...,26.0,1026.9,1022.4,NaN,NaN,9.5,18.6,No,0.0,No
142173,2017-06-05,Uluru,4.9,20.7,0.0,NaN,NaN,E,37.0,ESE,...,11.0,1027.1,1023.9,NaN,NaN,10.3,19.8,No,0.0,No
142174,2017-06-06,Uluru,1.2,20.8,0.0,NaN,NaN,E,43.0,ESE,...,6.0,1029.8,1025.9,NaN,NaN,7.9,19.9,No,0.0,No
142175,2017-06-07,Uluru,0.5,21.7,0.0,NaN,NaN,E,43.0,ESE,...,19.0,1029.0,1025.0,NaN,NaN,9.5,20.5,No,0.0,No
142176,2017-06-08,Uluru,4.0,20.0,0.0,NaN,NaN,SE,39.0,ESE,...,26.0,1030.2,1026.7,NaN,NaN,9.1,19.0,No,0.0,No
142177,2017-06-09,Uluru,3.4,19.8,0.0,NaN,NaN,E,43.0,ESE,...,23.0,1031.8,1027.7,NaN,NaN,8.7,18.9,No,0.0,No
142178,2017-06-10,Uluru,3.2,18.6,0.0,NaN,NaN,E,46.0,ESE,...,29.0,1031.0,1027.2,NaN,NaN,8.2,17.4,No,0.0,No
142179,2017-06-11,Uluru,2.4,19.1,0.0,NaN,NaN,E,33.0,SE,...,24.0,1030.0,1026.2,NaN,NaN,8.0,18.8,No,0.0,No
142180,2017-06-12,Uluru,5.1,19.7,0.0,NaN,NaN,E,46.0,ESE,...,29.0,1028.5,1025.8,NaN,NaN,8.5,19.2,No,0.0,No
142181,2017-06-13,Uluru,2.5,21.2,0.0,NaN,NaN,ENE,35.0,ESE,...,32.0,1027.2,1023.0,NaN,NaN,10.3,20.3,No,0.0,No
142182,2017-06-14,Uluru,2.3,21.4,0.0,NaN,NaN,SE,22.0,SE,...,28.0,1026.9,1022.8,NaN,NaN,8.9,20.3,No,0.0,No
142183,2017-06-15,Uluru,2.6,22.5,0.0,NaN,NaN,S,19.0,S,...,24.0,1025.0,1021.4,NaN,NaN,8.8,22.1,No,0.0,No
142184,2017-06-16,Uluru,5.2,24.3,0.0,NaN,NaN,E,24.0,SE,...,24.0,1023.8,1020.0,NaN,NaN,12.3,23.3,No,0.0,No
142185,2017-06-17,Uluru,6.4,23.4,0.0,NaN,NaN,ESE,31.0,S,...,25.0,1025.8,1023.0,NaN,NaN,11.2,23.1,No,0.0,No
142186,2017-06-18,Uluru,8.0,20.7,0.0,NaN,NaN,ESE,41.0,SE,...,32.0,1028.1,1024.3,NaN,7.0,11.6,20.0,No,0.0,No
142187,2017-06-19,Uluru,7.4,20.6,0.0,NaN,NaN,E,35.0,ESE,...,33.0,1027.2,1023.3,NaN,NaN,11.0,20.3,No,0.0,No
142188,2017-06-20,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0,ESE,...,27.0,1024.7,1021.2,NaN,NaN,9.4,20.9,No,0.0,No
142189,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,0.0,No
142190,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,0.0,No
142191,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,0.0,No
142192,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,0.0,No

In [174]:
## Vemos cuales variables presentan una falta de datos
df.isnull().sum()

Date                 0
Location             0
MinTemp            637
MaxTemp            322
Rainfall          1406
Evaporation      60843
Sunshine         67816
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Cloud9am         53657
Cloud3pm         57094
Temp9am            904
Temp3pm           2726
RainToday         1406
RISK_MM              0
RainTomorrow         0
dtype: int64

In [175]:
## Preparacion del dataset

# Para este modelo, no se utilizarán las variables cuyo % de ausencia sea mayor a 50 ya que al no haber sufientes daots, puede que
# afecten la predicciòn del modelo de manera inesperada. (cual será el valor ideal?)
# Se elimina Location para tratar de generalizarlo a otros lugares

df = df.drop(columns = ['Location', 'Evaporation', 'Sunshine', 'Cloud9am', 'Cloud3pm', 'RISK_MM'])
df.head()

,Date,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,13.4,22.9,0.6,W,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,No
1,2008-12-02,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,No
2,2008-12-03,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,No
3,2008-12-04,9.2,28.0,0.0,NE,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,No
4,2008-12-05,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,No

In [176]:
# Eliminar las filas cuyos valores categoricos no se encuentren presentes
df = df.dropna(subset=["WindGustDir"])
df = df.dropna(subset=["WindDir9am"])
df = df.dropna(subset=["WindDir3pm"])
df = df.dropna(subset=["RainToday"])

# Se llenan los valores numericos faltantes con el promedio de las columnas
df["MinTemp"].fillna(df["MinTemp"].mean(), inplace=True)
df["MaxTemp"].fillna(df["MaxTemp"].mean(), inplace=True)
df["Humidity9am"].fillna(df["Humidity9am"].mean(), inplace=True)
df["Humidity3pm"].fillna(df["Humidity3pm"].mean(), inplace=True)
df["Pressure9am"].fillna(df["Pressure9am"].mean(), inplace=True)
df["Pressure3pm"].fillna(df["Pressure3pm"].mean(), inplace=True)
df["Temp9am"].fillna(df["Temp9am"].mean(), inplace=True)
df["Temp3pm"].fillna(df["Temp3pm"].mean(), inplace=True)


df.isnull().sum()

Date             0
MinTemp          0
MaxTemp          0
Rainfall         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

In [177]:
# Transformacion de la fecha en dia del año. (por las estaciones)
a = pd.to_datetime(df["Date"], format='%Y-%m-%d').dt.dayofyear

# Tambien se transforman las variables categoricas a numericas
b = pd.get_dummies(df['WindGustDir'], prefix = "WGD")
c = pd.get_dummies(df['WindDir9am'], prefix = "WD9")
d = pd.get_dummies(df['WindDir3pm'], prefix = "WD3")
e = pd.get_dummies(df['RainToday'], prefix = "RT")

# Ejemplo de como queda la fecha
a[:5]

0    336
1    337
2    338
3    339
4    340
Name: Date, dtype: int64

In [178]:
# Concatenacion de los datos
frames = [a, b, c, d, e, df]
df = pd.concat(frames, axis = 1)
df = df.drop(columns = ['Date', 'WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday'])
df.head()

,WGD_E,WGD_ENE,WGD_ESE,WGD_N,WGD_NE,WGD_NNE,WGD_NNW,WGD_NW,WGD_S,WGD_SE,...,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainTomorrow
0,0,0,0,0,0,0,0,0,0,0,...,44.0,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No
1,0,0,0,0,0,0,0,0,0,0,...,44.0,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No
2,0,0,0,0,0,0,0,0,0,0,...,46.0,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No
3,0,0,0,0,1,0,0,0,0,0,...,24.0,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No
4,0,0,0,0,0,0,0,0,0,0,...,41.0,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No

In [179]:
X = df.iloc[0:len(df),:-1]
y = df.iloc[0:len(df),len(df.columns)-1:]

In [180]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .3, random_state=25)

from sklearn import tree

#Entrenamiento
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)

In [181]:
#Predicciones
y_pred = clf.predict(X_test)

#Evaluación del rendimiento del clasificador

from sklearn.metrics import confusion_matrix
confusion_matrix_tree = confusion_matrix(y_test, y_pred)

print()
print("Matriz de confusion")
print(confusion_matrix_tree)

#Print de la matriz de confusión

from sklearn.metrics import classification_report
print()
print("Recall y precision")
print(classification_report(y_test, y_pred))

Matriz de confusion
[[24764  4071]
 [ 3804  4474]]

Recall y precision
              precision    recall  f1-score   support

          No       0.87      0.86      0.86     28835
         Yes       0.52      0.54      0.53      8278

   micro avg       0.79      0.79      0.79     37113
   macro avg       0.70      0.70      0.70     37113
weighted avg       0.79      0.79      0.79     37113

In [182]:
## Modelo utilizando regresion logistica
from sklearn.linear_model import LogisticRegression

LogReg = LogisticRegression()
LogReg.fit(X_train, y_train)

print("coeficientes del modelo: "+str(LogReg.coef_))
print("intercept: "+str(LogReg.intercept_))

#Predicciones
y_pred = LogReg.predict(X_test)

#Evaluación del rendimiento del clasificador
from sklearn.metrics import confusion_matrix
confusion_matrix_log = confusion_matrix(y_test, y_pred)

print()
print("Matriz de confusion")
print(confusion_matrix_log)

print()
print("Recall y precision")
print(classification_report(y_test, y_pred))

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

coeficientes del modelo: [[-0.15999095 -0.11845182 -0.0656539   0.10998125 -0.23359102 -0.13277375
   0.1864941   0.13458675 -0.08441809  0.02795686 -0.03439645 -0.05567021
   0.09725157  0.12424386  0.15393212  0.09001835 -0.05581296  0.18075731
  -0.2007594   0.27412952  0.22548146  0.38264145  0.03305574 -0.0478632
  -0.20904173 -0.19976487 -0.16407934 -0.12853093 -0.0439924  -0.00446044
   0.05108329 -0.05332484 -0.0886964  -0.15099033 -0.10586781  0.18847877
  -0.36335307 -0.03008415  0.33942779  0.32315914 -0.04912022 -0.10338439
  -0.11992056 -0.0070409  -0.08320712  0.06749187  0.23605447 -0.01342844
  -0.26264994  0.3021686   0.04955489 -0.03573433  0.0109493   0.06476055
  -0.01687122 -0.03498133  0.0033041   0.06381992  0.1333225  -0.14067839
   0.01345191  0.00829604]]
intercept: [0.03951867]

Matriz de confusion
[[27313  1522]
 [ 4283  3995]]

Recall y precision
              precision    recall  f1-score   support

          No       0.86      0.95      0.90     28835
         Yes       0.72      0.48      0.58      8278

   micro avg       0.84      0.84      0.84     37113
   macro avg       0.79      0.71      0.74     37113
weighted avg       0.83      0.84      0.83     37113

In [189]:
# Finalmente, podemos ver que el modelo que utiliza la regresion logistica como algoritmo funciona mejor que el desicion tree 
# para este problema

accu_tree = (confusion_matrix_tree[0][0]+confusion_matrix_tree[1][1])/(confusion_matrix_tree[0][0] + confusion_matrix_tree[1][1] + confusion_matrix_tree[1][0]+confusion_matrix_tree[0][1])

accu_log = (confusion_matrix_log[0][0]+confusion_matrix_log[1][1])/(confusion_matrix_log[0][0] + confusion_matrix_log[1][1] + confusion_matrix_log[1][0]+confusion_matrix_log[0][1])

print("Accuracy Tree: " + str(accu_tree))
print("Accuracy Log: " + str(accu_log))

Accuracy Tree: 0.7878102012771805
Accuracy Log: 0.8435858055128931

In [186]:
# Otra posible solucion es utilizae el factor de riesgo RISK_MM para entrenar un modelo de regresion lineal y utilizar este numero
# mas nuestro criterio para evaluar

0.7878102012771805

In [191]:
# finalmente los datos utilizados son
X.keys()

Index(['WGD_E', 'WGD_ENE', 'WGD_ESE', 'WGD_N', 'WGD_NE', 'WGD_NNE', 'WGD_NNW',
       'WGD_NW', 'WGD_S', 'WGD_SE', 'WGD_SSE', 'WGD_SSW', 'WGD_SW', 'WGD_W',
       'WGD_WNW', 'WGD_WSW', 'WD9_E', 'WD9_ENE', 'WD9_ESE', 'WD9_N', 'WD9_NE',
       'WD9_NNE', 'WD9_NNW', 'WD9_NW', 'WD9_S', 'WD9_SE', 'WD9_SSE', 'WD9_SSW',
       'WD9_SW', 'WD9_W', 'WD9_WNW', 'WD9_WSW', 'WD3_E', 'WD3_ENE', 'WD3_ESE',
       'WD3_N', 'WD3_NE', 'WD3_NNE', 'WD3_NNW', 'WD3_NW', 'WD3_S', 'WD3_SE',
       'WD3_SSE', 'WD3_SSW', 'WD3_SW', 'WD3_W', 'WD3_WNW', 'WD3_WSW', 'RT_No',
       'RT_Yes', 'MinTemp', 'MaxTemp', 'Rainfall', 'WindGustSpeed',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Temp9am', 'Temp3pm'],
      dtype='object')